version: "3"

services:
  server:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    networks:
      - default
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
       - "8001:8000"
       - "9001:9000"

networks:
    default:
